---
title: "Share_Class_Charts"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'charts.html'))})
author: "Adrian D. Garcia"
date: "January 2020"
output: html_document
---

```{r setup, message=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(DT)
```

```{r load, message=FALSE}
LAUNCHES <- read_csv("Launches_Data.csv") %>% 
  select(Name,
         EXTRACT,
         Revision,
         `Share Class Type`,
         `US Category Group`,
         `Index Fund`,
         Ticker,
         `Firm Name`,
         `Inception Date`,
         `Inception Month`,
         `Inception Year`,
         `Same_Year`,
         `Obsolete Date`,
         `Obsolete Month`,
         `Obsolete Year`,
         `Obsolete Type`
         )

LIQUIDATIONS <- read_csv("Liquidations_Data.csv") %>% 
  select(Name,
         EXTRACT,
         Revision,
         `Share Class Type`,
         `US Category Group`,
         `Index Fund`,
         Ticker,
         `Firm Name`,
         `Inception Date`,
         `Inception Month`,
         `Inception Year`,
         `Same_Year`,
         `Obsolete Date`,
         `Obsolete Month`,
         `Obsolete Year`,
         `Obsolete Type`
         )
```

```{r overview}

Launches_Overview <- LAUNCHES %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Inception Year`) %>% 
  summarise(Launches = n()) %>% 
  filter(`Inception Year` != 2020)

Liquidations_Overview <- LIQUIDATIONS %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Obsolete Year`) %>% 
  summarise(Liquidations = n()) %>% 
  filter(`Obsolete Year` != 2020)

library(rJava)
library(xlsx)


write.xlsx(data.frame(Launches_Overview), "Charts.xlsx", sheetName="Launches_Overview", 
           col.names=TRUE, row.names=FALSE, append=FALSE)
write.xlsx(data.frame(Liquidations_Overview), "Charts.xlsx", sheetName="Liquidations_Overview",
           col.names=TRUE, row.names=FALSE, append=TRUE)

```

```{r classes}
Launches_Classes <- LAUNCHES %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Inception Year`, Revision) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Inception Year` != 2020) %>% 
  spread(`Inception Year`, TOTAL) %>% 
  arrange(-`2019`) %>% 
  head(n=15)

Liquidations_Classes <- LIQUIDATIONS %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Obsolete Year`, Revision) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Obsolete Year` != 2020) %>% 
  spread(`Obsolete Year`, TOTAL) %>% 
  arrange(-`2019`) %>% 
  head(n=15)

write.xlsx(data.frame(Launches_Classes), "Charts.xlsx", sheetName="Launches_Classes", 
           col.names=TRUE, row.names=FALSE, append=TRUE)
write.xlsx(data.frame(Liquidations_Classes), "Charts.xlsx", sheetName="Liquidations_Classes",
           col.names=TRUE, row.names=FALSE, append=TRUE)

```

```{r firms}
Launches_Firms <- LAUNCHES %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Inception Year`, `Firm Name`) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Inception Year` != 2020) %>% 
  spread(`Inception Year`, TOTAL) %>% 
  arrange(-`2019`) %>% 
  head(n=15)

Liquidations_Firms <- LIQUIDATIONS %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Obsolete Year`, `Firm Name`) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Obsolete Year` != 2020) %>% 
  spread(`Obsolete Year`, TOTAL) %>% 
  arrange(-`2019`) %>% 
  head(n=15)

write.xlsx(data.frame(Launches_Firms), "Charts.xlsx", sheetName="Launches_Firms", 
           col.names=TRUE, row.names=FALSE, append=TRUE)
write.xlsx(data.frame(Liquidations_Firms), "Charts.xlsx", sheetName="Liquidations_Firms",
           col.names=TRUE, row.names=FALSE, append=TRUE)

```

```{r type}
Launches_Types <- LAUNCHES %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Inception Year`, `US Category Group`) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Inception Year` != 2020) %>% 
  spread(`Inception Year`, TOTAL) %>% 
  arrange(-`2019`) %>% 
  head(n=15)

Liquidations_Types <- LIQUIDATIONS %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Obsolete Year`, `US Category Group`) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Obsolete Year` != 2020) %>% 
  spread(`Obsolete Year`, TOTAL) %>% 
  arrange(-`2019`) %>% 
  head(n=15)

write.xlsx(data.frame(Launches_Types), "Charts.xlsx", sheetName="Launches_Types", 
           col.names=TRUE, row.names=FALSE, append=TRUE)
write.xlsx(data.frame(Liquidations_Types), "Charts.xlsx", sheetName="Liquidations_Types",
           col.names=TRUE, row.names=FALSE, append=TRUE)

```

```{r uniquefirms}
Launches_UFirms <- LAUNCHES %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Inception Year`) %>% 
  summarise(TOTAL = length(unique(`Firm Name`))) %>% 
  filter(`Inception Year` != 2020) %>% 
  spread(`Inception Year`, TOTAL)

Liquidations_UFirms <- LIQUIDATIONS %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Obsolete Year`) %>%
  summarise(TOTAL = length(unique(`Firm Name`))) %>% 
  filter(`Obsolete Year` != 2020) %>% 
  spread(`Obsolete Year`, TOTAL)

write.xlsx(data.frame(Launches_UFirms), "Charts.xlsx", sheetName="Launches_Firm_Count", 
           col.names=TRUE, row.names=FALSE, append=TRUE)
write.xlsx(data.frame(Liquidations_UFirms), "Charts.xlsx", sheetName="Liquidations_Firm_Count",
           col.names=TRUE, row.names=FALSE, append=TRUE)

```

```{r obsolete}

Liquidations_Category <- LIQUIDATIONS %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Obsolete Year`, `Obsolete Type`) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Obsolete Year` != 2020) %>% 
  spread(`Obsolete Year`, TOTAL)


write.xlsx(data.frame(Liquidations_Category), "Charts.xlsx", sheetName="Liquidations_Category",
           col.names=TRUE, row.names=FALSE, append=TRUE)

```

```{r net_change}
a <- LAUNCHES %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Inception Year`, Revision) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Inception Year` != 2020) %>% 
  spread(`Inception Year`, TOTAL) %>% 
  arrange(-`2019`) %>%  
  select(1,6) %>% 
  mutate(
    `2019` = case_when(
      is.na(`2019`) ~ 0,
      TRUE ~ as.numeric(`2019`)
      )
    )

b <- LIQUIDATIONS %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Obsolete Year`, Revision) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Obsolete Year` != 2020) %>% 
  spread(`Obsolete Year`, TOTAL) %>%  
  select(1,6) %>%
  mutate(
    `2019` = case_when(
      is.na(`2019`) ~ 0,
      TRUE ~ as.numeric(`2019`)
      )
  )


Net_Change<- full_join(a,b, by = "Revision") %>%  
  mutate(`2019.x` = case_when(
      is.na(`2019.x`) ~ 0,
      TRUE ~ as.numeric(`2019.x`)),
      `2019.y` = case_when(
      is.na(`2019.y`) ~ 0,
      TRUE ~ as.numeric(`2019.y`)),
      NET_LOSS = (`2019.x` - `2019.y`))

write_csv(Net_Change, "net_change.csv")
rm(a)
rm(b)

```

```{r creators}
a <- LAUNCHES %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Inception Year`, `Firm Name`) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Inception Year` != 2020) %>% 
  spread(`Inception Year`, TOTAL) %>%  
  select(1,6) %>%
  mutate(
    `2019` = case_when(
      is.na(`2019`) ~ 0,
      TRUE ~ as.numeric(`2019`)
      )
    )

b <- LIQUIDATIONS %>% 
  filter(is.na(Same_Year) | Same_Year == 0) %>% 
  group_by(`Obsolete Year`, `Firm Name`) %>% 
  summarise(TOTAL = n()) %>% 
  filter(`Obsolete Year` != 2020) %>% 
  spread(`Obsolete Year`, TOTAL)  %>%  
  select(1,6) %>%
  mutate(
    `2019` = case_when(
      is.na(`2019`) ~ 0,
      TRUE ~ as.numeric(`2019`)
      )
    )

Creators <- full_join(a,b, by = "Firm Name") %>%  
  mutate(`2019.x` = case_when(
      is.na(`2019.x`) ~ 0,
      TRUE ~ as.numeric(`2019.x`)),
      `2019.y` = case_when(
      is.na(`2019.y`) ~ 0,
      TRUE ~ as.numeric(`2019.y`)),
      NET_LOSS = (`2019.x` - `2019.y`),
      Creation_Pct = `2019.x`/sum(`2019.x`) *100,
      Obsolete_Pct = `2019.y`/sum(`2019.y`) *100
      )

rm(a)
rm(b)
```

