---
title: "Share_Class"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Adrian D. Garcia"
date: "January 2020"
output: html_document
---

```{r setup, message=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(DT)
```

```{r INC_data, message=FALSE}

INCEPTION <-
  read_excel(path = "launch-liquidation-data-for-adrian.xlsx", sheet = 1, na = "")

PATTERN <-
  c(
    "(\\s)?([:alnum:]+)?([:alnum:][:punct:][:alnum:] LW)?( Load Waived)?( LW)?([:punct:]+)?([:alnum:]+)?(-[:alnum:])?(™)?([:alpha:]\\{..\\} LW)?([:punct:]..[:punct:])?(\\s)?([:punct:][:alpha:]+[:punct:])?$"
  )

CUT <-
  c(
    "([:punct:]\\X\\X[:punct:])|([:punct:]\\X\\X$)|(-)|(\\sLW)|(\\sLoad\\sWaived)|(\\([:alpha:]+\\))"
  )

CHANGE <- c(
  "^Adm(in$)?(in[:alpha:]+)?$" = "Admin",
  "[:alnum:]+R6$" = "R6",
  "(?!AA)[:alpha:]+A$" = "A",
  "A\\{m" = "A",
  "([:alpha:]+)([:punct:])?([:alpha:]+)?A$" = "A",
  "(?![FIVS]+I$|([:alpha:]+)?II$)([:alpha:]+)?I$(?<!(IR$))" = "I",
  "([:alpha:]+)([:punct:])?([:alpha:]+)?I$(?<!(F/I$))" = "I",
  "([:alpha:]+)([:punct:])?([:alpha:]+)?C$" = "C",
  "PlusC([:digit:]+)$" = "C",
  "([:alpha:]+)?([:Punct:][:alpha:]+)?Inst(l$)?(itutional$)?$" = "Instl",
  "([:alnum:]+)?Ins$" = "Instl",
  "([:alnum:]+)?Insl$" = "Instl",
  "[:alnum:]+Ist$" = "Instl",
  "([:alpha:]+)?([:punct:])?([:alpha:]+)?Y$" = "Y",
  "([:alpha:]+)?([:punct:])?([:alpha:]+)?R$(?<!(SDR$)|(IR$))" = "R",
  "[:alnum:]+R5$" = "R5",
  "([:alpha:]+)?([:Punct:][:alpha:]+)?In([vest]+)?(ment$)?$(?<!(Int$))" = "Investor",
  "([:alpha:]+)?([:punct:])?([:alpha:]+)?N$" = "N",
  "([:alpha:]+)?([:punct:])?([:alpha:]+)?T$" = "T",
  "[:alnum:]+R4$" = "R4",
  "([:alpha:]+)?([:Punct:][:alpha:]+)?Adv(iser$)?(isory$)?$" = "Advisor",
  "([:alpha:]+)?([:Punct:][:alpha:]+)?ADV$" = "Advisor",
  "([:alpha:]+)?([:punct:])?([:alpha:]+)?K$" = "K",
  "([:alpha:]+)?([:punct:])?([:alpha:]+)?F$" = "F",
  "[:alnum:]+R3$" = "R3",
  "[:alnum:]+F3$" = "F3",
  "([:alpha:]+)?([:punct:])?([:alpha:]+)?IS$" = "IS",
  "^I$" = "Instl",
  "Retire(ment)?$" = "R"
)

INC_Data <- INCEPTION %>%
  select(Name) %>%
  mutate(
    Match = str_detect(Name, PATTERN),
    EXTRACT = str_extract(Name, PATTERN),
    New = str_trim(str_replace_all(EXTRACT,  CUT, "")),
    Revision = str_replace_all(New, CHANGE)
    )
```

```{r INC_data_show, echo=FALSE}
datatable(INC_Data, options = list(autoWidth = TRUE, scrollX = TRUE))
```

```{r INC_summary, message=FALSE}
INC_Changes <- INC_Data %>%
  group_by(EXTRACT) %>%
  summarise(cases = n()) %>%
  mutate(New = str_trim(str_replace_all(EXTRACT,  CUT, ""))) %>% group_by(New) %>%
  mutate(replacements = n() - 1,
         newcases = sum(cases)) %>%
  mutate(Revision = str_replace_all(New, CHANGE)) %>%
  group_by(Revision) %>%
  mutate(replacements1 = (n() - replacements) - 1,
         newercases = sum(cases))

INC_Summary <- INC_Data %>%
  group_by(Revision) %>%
  summarise(cases = n()) %>%
  arrange(-cases)
```

```{r INC_changes_summary_show, echo=FALSE}
datatable(INC_Changes)
```

```{r INC_add, message=FALSE}
INC_MODIFIED <- INCEPTION %>%
  mutate(
    Match = str_detect(Name, PATTERN),
    EXTRACT = str_extract(Name, PATTERN),
    New = str_trim(str_replace_all(EXTRACT,  CUT, "")),
    Revision = str_replace_all(New, CHANGE),
    `Inception Year` = year(`Inception Date`),
    `Inception Month` = month(`Inception Date`)
  ) %>%
  select(Name, Match, EXTRACT, New, Revision, 2:3, `Inception Month`, `Inception Year`, 4:19)

write.csv(INC_MODIFIED, "Launches_Data.csv")

```

```{r INC_summary_show, echo=FALSE}
datatable(INC_Summary)
```

```{r LIQUIDATION}
LIQUIDATION <-
  read_excel(path = "launch-liquidation-data-for-adrian.xlsx", sheet = 2, na = "")

LIQ_Data <- LIQUIDATION %>%
  select(Name) %>%
  mutate(
    Match = str_detect(Name, PATTERN),
    EXTRACT = str_extract(Name, PATTERN),
    New = str_trim(str_replace_all(EXTRACT,  CUT, "")),
    Revision = str_replace_all(New, CHANGE)
    )
```

```{r LIQ_summary, message=FALSE}
LIQ_Changes <- LIQ_Data %>%
  group_by(EXTRACT) %>%
  summarise(cases = n()) %>%
  mutate(New = str_trim(str_replace_all(EXTRACT,  CUT, ""))) %>% group_by(New) %>%
  mutate(replacements = n() - 1,
         newcases = sum(cases)) %>%
  mutate(Revision = str_replace_all(New, CHANGE)) %>%
  group_by(Revision) %>%
  mutate(replacements1 = (n() - replacements) - 1,
         newercases = sum(cases))

LIQ_Summary <- LIQ_Data %>%
  group_by(Revision) %>%
  summarise(cases = n()) %>%
  arrange(-cases)
```

```{r LIQ_add, message=FALSE}
LIQ_MODIFIED <- LIQUIDATION %>%
  mutate(
    Match = str_detect(Name, PATTERN),
    EXTRACT = str_extract(Name, PATTERN),
    New = str_trim(str_replace_all(EXTRACT,  CUT, "")),
    Revision = str_replace_all(New, CHANGE),
    `Obsolete Year` = year(`Obsolete Date`),
    `Obsolete Month` = month(`Obsolete Date`)
  ) %>%
  select(Name, Match, EXTRACT, New, Revision, 2:3, `Obsolete Month`, `Obsolete Year`, 4:25)

write.csv(LIQ_MODIFIED, "Liquidations_Data.csv")

```

```{r explore, message=FALSE}
Merged_in_2019 <- inner_join(INC_MODIFIED,LIQ_MODIFIED) %>% 
  filter(., `Obsolete Type` == "Merged") %>% 
  mutate(Same_Year =
           if_else(`Inception Year` == `Obsolete Year`, 1, 0) 
         ) %>% 
  filter(Same_Year == 1 & `Inception Year` == 2019)

Disolved <- inner_join(INC_MODIFIED,LIQ_MODIFIED) %>% 
  mutate(., Same_Year =
           if_else(`Inception Year` == `Obsolete Year`, 1, 0)
  )

Launches_Caveat <- left_join(INC_MODIFIED, Disolved)
Liquidations_Caveat <- left_join(LIQ_MODIFIED, Disolved)


```

